#!/bin/bash
# Copyright (C) 2021 MyGpack

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# error precaution.
set -e
# default unzip folder.
git init
DIR='app/main'
mkdir -p "$DIR"

_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO =~ $regex ]]
    then 
        echo "${UPSTREAM_REPO}/archive/alpha.zip"
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2NvZGUtcmdiL1VTRVJHRS1YL2FyY2hpdmUvYWxwaGEuemlw" | base64 -d
    fi
}

_startbot () {
    cd $DIR/*
    echo -e "\n\n   >><< --- >><< ---=>  Starting [X]  <=--- >><< --- >><<\n\n"
    sleep 5
    bash run
}

setup_repo () {
    local zippath
    zippath="app/temp.zip"
    echo -e "--->  Fetching Update from Upstream Repo ..."
    wget -q $(_get_ziplink) -O "$zippath"
    echo -e "      Done\n"
    echo "--->  Unpacking Data ..."
    unzip -qq "$zippath" -d "$DIR"
    echo -e "      Done\n"
    echo "--->  Cleaning ..."
    rm -rf "$zippath"
    echo "      Done"
    sleep 2
    _startbot
}

setup_repo
